name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.0.0
  flutter_riverpod: ^2.0.0
  image_picker: ^0.8.5+3
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  url_launcher: ^6.1.6
  flutter_hooks: ^0.20.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
